spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backstage?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://47.93.244.195:3306/backstage?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 9000
  tomcat:
    accept-count: 200
    max-connections: 200
    max-http-header-size: 209715200
    max-http-form-post-size: 200

mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
mybatis-plus:
  type-aliases-package: com.shenxiang.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml


